version: "3.7"
name: wallet-app

services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
          - 27017:27017
        volumes:
          - mongodata:/data/db

    sqlserver:
         image: mcr.microsoft.com/mssql/server:2022-latest
         container_name: sqlserver
         ports:
           - 1433:1433
         environment:
           - MSSQL_SA_PASSWORD=Password@1234
           - ACCEPT_EULA=Y
         volumes:
           - sqlserver:/var/opt/mssql

    exchangerates-api:
         image: exchangerates-api-latest
         container_name: exchangerates-api
         build:
           context: .
           dockerfile: ./ExchangeRates.API/Dockerfile
         ports:
           - 5001:80
         depends_on:
           - mongo
    
    exchangerates-backgroundtasks:
         image: exchangerates-backgroundtasks-latest
         container_name: exchangerates-backgroundtasks
         build:
           context: .
           dockerfile: ./ExchangeRates.BackgroundTasks/Dockerfile
         depends_on:
           - mongo
 
    wallet-api:
         image: wallet-api-latest
         container_name: wallet-api
         build:
           context: .
           dockerfile: ./Wallet.API/Dockerfile
         ports:
           - 5002:80
         depends_on:
           - sqlserver
           - exchangerates-api


volumes:
  mongodata:
    external: false
  sqlserver:
    external: false
